version: '3'

services:
  builder:
    build:
      context: .
      args:
        - CIRCLE_SHA1
        - PROJECT
    image: damacus/docker-builder:latest
    container_name: docker-builder
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
