version: 2
jobs:
  test:
    docker:
      - image: circleci/golang
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker-compose build

  build_and_deploy:
    docker:
      - image: circleci/golang
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker-compose build
      - deploy:
          name: Push Image
          context: org-global
          command: |
            docker login -u "${DOCKER_LOGIN:?}" -p "${DOCKER_PASSWORD:?}"
            docker-compose push builder
            docker tag damacus/docker-builder:latest damacus/docker-builder:${CIRCLE_BUILD_NUM}
            docker push damacus/docker-builder:${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  build:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              ignore: [master]
      - build_and_deploy:
          context: org-global
          filters:
            branches:
              only: [master]
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only: [master]
    jobs:
      - build_and_deploy:
          context: org-global
